### PR TITLE
Edits to Budgie and XFCE sections

### PR DESCRIPTION
**Pull request by EbonJaeger**

### CODE REVIEW

**Comment by EbonJaeger** [comment]
I... wat? GitHub, where's my stuff? xD

**Comment by EbonJaeger** [comment]
Derp it helps if I save the file first.

**Review by davidjharder — APPROVED** [review]

**Comment by davidjharder** [comment]
@EbonJaeger can you also look at what I wrote for XFCE for the various other pages on the site: https://github.com/davidjharder/solus-hugo-theme-djh/commit/57e4ec08589785f744e1f42c4a9a3498d6e722c9

**Comment by davidjharder** [comment]
Also this https://github.com/davidjharder/solus-site.github.io/commit/6a2901ac3d18b5501d5f626c2ac731622bb64e9b

**Comment by EbonJaeger** [comment]
Yeah, they look good to me.

**Pull request merged**
